version: '3.9'
services:
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app/apg-tool
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
