import Head from 'next/head';
import { FC } from 'react';
import { ListGroup } from 'react-bootstrap';
import Link from 'next/link';

const WikiPage: FC = () => {
  return (
    <>
      <Head>
        <title>APG tool project: wiki page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main className='main'>
        <h2>
          Here few examples how to use APG tool with additional parameters:
        </h2>
        <ListGroup as='ol' numbered>
          <ListGroup.Item as='li'>
            Generate a random password (default password length is 8): just
            press `APG tool`
          </ListGroup.Item>
          <ListGroup.Item as='li'>
            Create a password containing at least 1 special character (S), 1
            number (N), 1 uppercase letter, 1 lowercase letter (L): `-M SNCL`
          </ListGroup.Item>
          <ListGroup.Item as='li'>
            Create a password no shorter than 16 characters: `-m 16`
          </ListGroup.Item>
          <ListGroup.Item as='li'>
            Create a password no longer than 16 characters: `-x 16`
          </ListGroup.Item>
          <ListGroup.Item as='li'>
            Create a password that is not found in the dictionary (you must
            provide a dictionary file): `-r dictionary_file`
          </ListGroup.Item>
        </ListGroup>
        <div>
          <Link
            data-testid='nav-wiki'
            className='nav-item nav-link active'
            href='https://linux.die.net/man/1/apg'
            target='_blank'
            style={{
              textDecoration: 'underline',
              color: 'blue',
              fontSize: 17,
              marginTop: '25px',
            }}
          >
            More information: APG
          </Link>
        </div>
      </main>
    </>
  );
};

export default WikiPage;
